# Site settings
title: dzufferey's blog
# email: your-email@domain.com
description: "Damien Zufferey's blog: description of my projects and some random rambling"
baseurl: ""
url: "http://dzufferey.github.io"
# twitter_username: jekyllrb
github_username:  dzufferey

# Build settings
markdown: kramdown
permalink: pretty
